name: echeckout_ipg_flutter
description: eCheckout IPG SDK for Flutter
version: 3.0.0
repository: https://github.com/payable/flutter-ipg-echeckoutlk

environment:
  sdk: ">=2.17.6 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  webview_flutter: ^4.7.0
  http: ^1.2.1
  package_info: ^2.0.0
  crypto: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2